#!/usr/bin/env python3.8

import sys
import os
from os.path import abspath

interpreter="python3.8"

if len(sys.argv) == 1:
    sys.argv.append("-h")

if sys.argv[1] in ["-h","--help","getopt","usage","help","-help"]:

    print("""

    --------------------------------------------------------------------------------
    all2vcf
    v 0.4.0
    Matteo Schiavinato
    Core Facility Bioinformatics - University of Natural Resources and Life Sciences
    Vienna, Austria
    2021
    --------------------------------------------------------------------------------
    Toolkit to convert and process different variant calling formats into VCF
    --------------------------------------------------------------------------------

    [conversion]
    isec            Convert the \"sites.txt\" output file of bcftools isec to VCF
    mummer          Convert the result of \"show-snps -T\" to a psuedo-VCF file

    [statistics]
    density         Count variants and variants per kbp from a VCF file
    stats           Count occurrences of variants inside the provided VCF files


    """)

else:
    args = " ".join(sys.argv[1:])
    PROGRAMDIR = os.path.dirname(os.path.realpath(__file__))
    os.system(f"{interpreter} {PROGRAMDIR}/src/{args}")
